spring.datasource.url=jdbc:mysql://localhost:3306/sgb
spring.datasource.username=root
spring.datasource.password=Costacampelo1@

# Especifica o que fazer com o BD: update -> Cria as tabelas e mantem quando fecha ou inicia a aplicação
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=truex